name: Vroom CI
on:
  pull_request:
    branches:
      - master
jobs:
  vroom:
    strategy:
      matrix: 
        cxx: ['g++-9', 'clang++-10']
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install libasio-dev libglpk-dev jq
      - name: Make
        run: make
        env:
          CXX: ${{ matrix.cxx }}
        working-directory: src
      - name: Validate output
        run: diff <(bin/vroom -i docs/example_2.json  | jq '.routes[].steps[]' --sort-keys) <(jq '.routes[].steps[]' --sort-keys docs/example_2_sol.json)
